---
# tasks file for ansible-qdevice-role
- name: Install required packages
  yum:
    name:
    - pcs
    - corosync-qnetd
- name: Start and Enable pcsd.service
  systemd:
    name: pcsd
    enabled: true
    state: started
- name: Setup quorum device
  command: pcs qdevice setup model net --enable --start
  create: /etc/corosync/qnetd/nssdb/qnetd-cacert.crt
