---
# tasks file for ansible-qdevice-role
- name: Install required packages
  yum:
    name:
    - pcs
    - corosync_qnetd
- name: Start and Enable pcsd.service
  systemd:
    name: pcsd
    enabled: true
    state: started
- name: Setup quorum device
  shell: pcs qdevice status net --full

